# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Bio
    url: 'https://drwenjielan.github.io/#bio'
    weight: 9
  - name: Reseach Interest
    url: 'https://drwenjielan.github.io/#mission'
    weight: 10
  - name: Research
    url: 'https://drwenjielan.github.io/#research'
    weight: 11    
  - name: Projects
    url: 'https://drwenjielan.github.io/#projects'
    weight: 20
  - name: Education & Work
    url: 'https://drwenjielan.github.io/#education'
    weight: 30
  - name: Skills
    url: 'https://drwenjielan.github.io/#skill'
    weight: 50
  - name: Awards
    url: 'https://drwenjielan.github.io/#awards'
    weight: 60
#  - name: Teaching
#    url: teaching/
#    weight: 40
